#!/bin/bash
# 🚀 SCRIPT DE INICIALIZAÇÃO DO PROJETO

echo "╔════════════════════════════════════════════════════════════╗"
echo "║   TCC VIAGEM - Sistema Completo de Planejamento          ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ Seu projeto está pronto para iniciar!"
echo ""
echo "📋 ARQUIVOS CRIADOS:"
echo "   ✅ Backend (Node.js/Express)"
echo "   ✅ Frontend (React/Vite)"
echo "   ✅ API Service (services/api.js)"
echo "   ✅ Database Schema (schema.sql)"
echo "   ✅ Documentação Completa"
echo ""
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "🎯 PRÓXIMAS AÇÕES (em ordem):"
echo ""
echo "1️⃣  ABRIR HEIDISQL"
echo "    └─ Conectar a localhost:3306 (root/1234)"
echo "    └─ Criar banco: tcc_viagem"
echo "    └─ Executar: Backend/schema.sql"
echo "    Tempo: ~5 minutos"
echo ""
echo "2️⃣  TESTAR BACKEND"
echo "    └─ cd Backend"
echo "    └─ node server.js"
echo "    └─ Abrir: http://localhost:3000/test-connection"
echo "    Tempo: ~2 minutos"
echo ""
echo "3️⃣  TESTAR FRONTEND"
echo "    └─ cd FrontEnd"
echo "    └─ npm install (1ª vez apenas)"
echo "    └─ npm run dev"
echo "    └─ Abrir: http://localhost:5173"
echo "    Tempo: ~3 minutos"
echo ""
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "📚 DOCUMENTAÇÃO DISPONÍVEL:"
echo "   📖 SETUP.md ........................ Guia visual 3 passos"
echo "   📖 INDICE.md ....................... Índice de documentação"
echo "   📖 QUICKSTART.md ................... Resumo rápido"
echo "   📖 CONFIGURAR_BANCO.md ............ Passo a passo detalhado"
echo "   📖 VISAO_GERAL.md .................. Diagramas visuais"
echo "   📖 BANCO_DADOS.md .................. Documentação técnica"
echo "   📖 EXEMPLOS_API.md ................. Exemplos de requisições"
echo "   📖 ARQUITETURA.md .................. Fluxos visuais"
echo ""
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "🔑 CREDENCIAIS DO BANCO:"
echo "   Host:     localhost"
echo "   User:     root"
echo "   Password: 1234"
echo "   Port:     3306"
echo "   Database: tcc_viagem"
echo ""
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "💻 SERVIÇOS RODANDO:"
echo "   Backend:  http://localhost:3000"
echo "   Frontend: http://localhost:5173"
echo "   MariaDB:  localhost:3306"
echo ""
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "✨ TECNOLOGIAS USADAS:"
echo "   Backend:    Node.js + Express"
echo "   Frontend:   React + Vite"
echo "   Database:   MariaDB"
echo "   Auth:       bcrypt (senhas seguras)"
echo "   CORS:       Configurado"
echo "   API:        RESTful"
echo ""
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "🎯 PRONTO PARA COMEÇAR!"
echo ""
echo "➡️  Próximo passo: Abra SETUP.md ou INDICE.md"
echo ""
echo "═════════════════════════════════════════════════════════════"
